[project]
name = "expedition33"
version = "0.1.0"
description = "Clair Obscure: Expedition 33 Database"
#authors = ["Test <w/e@example.com>"]
license = {text = "MIT"}

# runtime dependencies
dependencies = [
    "dash==4.0.0",
    "dash-bootstrap-components==2.0.4",
    "gunicorn==25.1.0",
]